export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: " LOGOUT_SUCCESS",
  LOGOUT_FAILED: " LOGOUT_FAILED",
};

export const userConstants = {
  USER_SIGNUP_REQUEST: "USER_SIGNUP_REQUEST",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAILED: "USER_SIGNUP_FAILED",
};

export const categoryConstants={
  GET_ALL_CATEGORY_REQUEST:"GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS:"GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILED:"GET_ALL_CATEGORY_FAILED",
  
  ADD_CATEGORY_REQUEST:"ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_SUCCESS:"ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAILED:"ADD_CATEGORY_FAILED",
}

export const productConstants={

  GET_ALL_PRODUCTS_REQUEST:"GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS:"GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILED:"GET_ALL_PRODUCTS_FAILED",

  ADD_PRODUCTS_REQUEST:"ADD_PRODUCTS_REQUEST",
  ADD_PRODUCTS_SUCCESS:"ADD_PRODUCTS_SUCCESS",
  ADD_PRODUCTS_FAILED:"ADD_PRODUCTS_FAILED",

}


